<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('countries')->delete();
        
        \DB::table('countries')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => '{"en":"United States","pl":"United States","jp":"United States","ja":"United States","es":"United States","th":"United States"}',
                'created_at' => NULL,
                'updated_at' => '2021-02-23 19:10:33',
                'iso3' => 'USA',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => '{"en":"Argentina","pl":"Argentina","jp":"Argentina","ja":"Argentina","es":"Argentina","th":"Argentina"}',
                'created_at' => NULL,
                'updated_at' => '2021-05-28 10:05:27',
                'iso3' => 'ARG',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 5,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => '{"en":"Australia","pl":"Australia","jp":"Australia","ja":"Australia","es":"Australia","th":"Australia"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'AUS',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => '{"en":"Austria","pl":"Austria","jp":"Austria","ja":"Austria","es":"Austria","th":"Austria"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'AUT',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => '{"en":"Belgium","pl":"Belgium","jp":"Belgium","ja":"Belgium","es":"Belgium","th":"Belgium"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'BEL',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => '{"en":"Brazil","pl":"Brazil","jp":"Brazil","ja":"Brazil","es":"Brazil","th":"Brazil"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'BRA',
                'currency' => 'usd',
                'is_active' => 0,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 5,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 0,
                'has_residence' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => '{"en":"Bulgaria","pl":"Bulgaria","jp":"Bulgaria","ja":"Bulgaria","es":"Bulgaria","th":"Bulgaria"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'BGR',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => '{"en":"Canada","pl":"Canada","jp":"Canada","ja":"Canada","es":"Canada","th":"Canada"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'CAN',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => '{"en":"Canary Islands","pl":"Canary Islands","jp":"Canary Islands","ja":"Canary Islands","es":"Canary Islands","th":"Canary Islands"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'CAI',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => '{"en":"Chile","pl":"Chile","jp":"Chile","ja":"Chile","es":"Chile","th":"Chile"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'CHL',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 5,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => '{"en":"Colombia","pl":"Colombia","jp":"Colombia","ja":"Colombia","es":"Colombia","th":"Colombia"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'COL',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 5,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => '{"en":"Costa Rica","pl":"Costa Rica","jp":"Costa Rica","ja":"Costa Rica","es":"Costa Rica","th":"Costa Rica"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'CRI',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => '{"en":"Cyprus","pl":"Cyprus","jp":"Cyprus","ja":"Cyprus","es":"Cyprus","th":"Cyprus"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'CYP',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => '{"en":"Czech Republic","pl":"Czech Republic","jp":"Czech Republic","ja":"Czech Republic","es":"Czech Republic","th":"Czech Republic"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'CZE',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => '{"en":"Denmark","pl":"Denmark","jp":"Denmark","ja":"Denmark","es":"Denmark","th":"Denmark"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'DNK',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => '{"en":"Dominican Republic","pl":"Dominican Republic","jp":"Dominican Republic","ja":"Dominican Republic","es":"Dominican Republic","th":"Dominican Republic"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'DOM',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => '{"en":"Ecuador","pl":"Ecuador","jp":"Ecuador","ja":"Ecuador","es":"Ecuador","th":"Ecuador"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'ECU',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 5,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            17 => 
            array (
                'id' => 19,
                'name' => '{"en":"Estonia","pl":"Estonia","jp":"Estonia","ja":"Estonia","es":"Estonia","th":"Estonia"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'EST',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            18 => 
            array (
                'id' => 20,
                'name' => '{"en":"Finland","pl":"Finland","jp":"Finland","ja":"Finland","es":"Finland","th":"Finland"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'FIN',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            19 => 
            array (
                'id' => 21,
                'name' => '{"en":"France","pl":"France","jp":"France","ja":"France","es":"France","th":"France"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'FRA',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            20 => 
            array (
                'id' => 22,
                'name' => '{"en":"Germany","pl":"Germany","jp":"Germany","ja":"Germany","es":"Germany","th":"Germany"}',
                'created_at' => NULL,
                'updated_at' => '2021-02-23 17:12:05',
                'iso3' => 'DEU',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '2500.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            21 => 
            array (
                'id' => 23,
                'name' => '{"en":"Greece","pl":"Greece","jp":"Greece","ja":"Greece","es":"Greece","th":"Greece"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'GRC',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            22 => 
            array (
                'id' => 24,
                'name' => '{"en":"Hong Kong","pl":"Hong Kong","jp":"Hong Kong","ja":"Hong Kong","es":"Hong Kong","th":"Hong Kong"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'HKG',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            23 => 
            array (
                'id' => 25,
                'name' => '{"en":"Hungary","pl":"Hungary","jp":"Hungary","ja":"Hungary","es":"Hungary","th":"Hungary"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'HUN',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            24 => 
            array (
                'id' => 26,
                'name' => '{"en":"Indonesia","pl":"Indonesia","jp":"Indonesia","ja":"Indonesia","es":"Indonesia","th":"Indonesia"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'IDN',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            25 => 
            array (
                'id' => 27,
                'name' => '{"en":"Ireland","pl":"Ireland","jp":"Ireland","ja":"Ireland","es":"Ireland","th":"Ireland"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'IRL',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            26 => 
            array (
                'id' => 28,
                'name' => '{"en":"Italy","pl":"Italy","jp":"Italy","ja":"Italy","es":"Italy","th":"Italy"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'ITA',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            27 => 
            array (
                'id' => 29,
                'name' => '{"en":"Japan","pl":"Japan","jp":"Japan","ja":"Japan","es":"Japan","th":"Japan"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'JPN',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            28 => 
            array (
                'id' => 31,
                'name' => '{"en":"Latvia","pl":"Latvia","jp":"Latvia","ja":"Latvia","es":"Latvia","th":"Latvia"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'LVA',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            29 => 
            array (
                'id' => 32,
                'name' => '{"en":"Lithuania","pl":"Lithuania","jp":"Lithuania","ja":"Lithuania","es":"Lithuania","th":"Lithuania"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'LTU',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            30 => 
            array (
                'id' => 33,
                'name' => '{"en":"Luxembourg","pl":"Luxembourg","jp":"Luxembourg","ja":"Luxembourg","es":"Luxembourg","th":"Luxembourg"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'LUX',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            31 => 
            array (
                'id' => 34,
                'name' => '{"en":"Macau","pl":"Macau","jp":"Macau","ja":"Macau","es":"Macau","th":"Macau"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'MAC',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            32 => 
            array (
                'id' => 35,
                'name' => '{"en":"Malta","pl":"Malta","jp":"Malta","ja":"Malta","es":"Malta","th":"Malta"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'MLT',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            33 => 
            array (
                'id' => 36,
                'name' => '{"en":"Monaco","pl":"Monaco","jp":"Monaco","ja":"Monaco","es":"Monaco","th":"Monaco"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'MCO',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            34 => 
            array (
                'id' => 37,
                'name' => '{"en":"Netherlands","pl":"Netherlands","jp":"Netherlands","ja":"Netherlands","es":"Netherlands","th":"Netherlands"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'NLD',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            35 => 
            array (
                'id' => 38,
                'name' => '{"en":"New Zealand","pl":"New Zealand","jp":"New Zealand","ja":"New Zealand","es":"New Zealand","th":"New Zealand"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'NZL',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '650.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            36 => 
            array (
                'id' => 39,
                'name' => '{"en":"Norway","pl":"Norway","jp":"Norway","ja":"Norway","es":"Norway","th":"Norway"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'NOR',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            37 => 
            array (
                'id' => 40,
                'name' => '{"en":"Panama","pl":"Panama","jp":"Panama","ja":"Panama","es":"Panama","th":"Panama"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'PAN',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            38 => 
            array (
                'id' => 41,
                'name' => '{"en":"Peru","pl":"Peru","jp":"Peru","ja":"Peru","es":"Peru","th":"Peru"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'PER',
                'currency' => 'usd',
                'is_active' => 0,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 10,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 0,
                'has_residence' => 1,
            ),
            39 => 
            array (
                'id' => 42,
                'name' => '{"en":"Philippines","pl":"Philippines","jp":"Philippines","ja":"Philippines","es":"Philippines","th":"Philippines"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'PHL',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            40 => 
            array (
                'id' => 43,
                'name' => '{"en":"Poland","pl":"Poland","jp":"Poland","ja":"Poland","es":"Poland","th":"Poland"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'POL',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            41 => 
            array (
                'id' => 44,
                'name' => '{"en":"Portugal","pl":"Portugal","jp":"Portugal","ja":"Portugal","es":"Portugal","th":"Portugal"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'PRT',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            42 => 
            array (
                'id' => 45,
                'name' => '{"en":"Romania","pl":"Romania","jp":"Romania","ja":"Romania","es":"Romania","th":"Romania"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'ROU',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            43 => 
            array (
                'id' => 46,
                'name' => '{"en":"Singapore","pl":"Singapore","jp":"Singapore","ja":"Singapore","es":"Singapore","th":"Singapore"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'SGP',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            44 => 
            array (
                'id' => 47,
                'name' => '{"en":"Slovakia","pl":"Slovakia","jp":"Slovakia","ja":"Slovakia","es":"Slovakia","th":"Slovakia"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'SVK',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            45 => 
            array (
                'id' => 48,
                'name' => '{"en":"Slovenia","pl":"Slovenia","jp":"Slovenia","ja":"Slovenia","es":"Slovenia","th":"Slovenia"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'SVN',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            46 => 
            array (
                'id' => 49,
                'name' => '{"en":"South Africa","pl":"South Africa","jp":"South Africa","ja":"South Africa","es":"South Africa","th":"South Africa"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'ZAF',
                'currency' => 'usd',
                'is_active' => 0,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 5,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 0,
                'has_residence' => 1,
            ),
            47 => 
            array (
                'id' => 50,
                'name' => '{"en":"Spain","pl":"Spain","jp":"Spain","ja":"Spain","es":"Spain","th":"Spain"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'ESP',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            48 => 
            array (
                'id' => 51,
                'name' => '{"en":"Sweden","pl":"Sweden","jp":"Sweden","ja":"Sweden","es":"Sweden","th":"Sweden"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'SWE',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            49 => 
            array (
                'id' => 52,
                'name' => '{"en":"Switzerland","pl":"Switzerland","jp":"Switzerland","ja":"Switzerland","es":"Switzerland","th":"Switzerland"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'CHE',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            50 => 
            array (
                'id' => 53,
                'name' => '{"en":"Taiwan","pl":"Taiwan","jp":"Taiwan","ja":"Taiwan","es":"Taiwan","th":"Taiwan"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'TWN',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            51 => 
            array (
                'id' => 54,
                'name' => '{"en":"United Kingdom","pl":"United Kingdom","jp":"United Kingdom","ja":"United Kingdom","es":"United Kingdom","th":"United Kingdom"}',
                'created_at' => NULL,
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'GBR',
                'currency' => 'gbp',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            52 => 
            array (
                'id' => 56,
                'name' => '{"en":"Malaysia","pl":"Malaysia","jp":"Malaysia","ja":"Malaysia","es":"Malaysia","th":"Malaysia"}',
                'created_at' => '2017-04-03 21:48:23',
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'MYS',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            53 => 
            array (
                'id' => 57,
                'name' => '{"en":"China","pl":"China","jp":"China","ja":"China","es":"China","th":"China"}',
                'created_at' => '2017-06-30 15:46:00',
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'CHN',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '300.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            54 => 
            array (
                'id' => 60,
                'name' => '{"en":"Croatia","pl":"Croatia","jp":"Croatia","ja":"Croatia","es":"Croatia","th":"Croatia"}',
                'created_at' => '2017-11-07 23:32:10',
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'HRV',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            55 => 
            array (
                'id' => 61,
                'name' => '{"en":"South Korea","pl":"South Korea","ja":"South Korea","es":"South Korea","th":"South Korea"}',
                'created_at' => '2018-04-11 18:05:32',
                'updated_at' => '2021-02-09 23:00:54',
                'iso3' => 'KOR',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '0.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 6,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            56 => 
            array (
                'id' => 62,
                'name' => '{"en":"Thailand","pl":"Thailand","ja":"Thailand","es":"Thailand","th":"Thailand"}',
                'created_at' => '2018-05-21 05:26:35',
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'THA',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 10,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            57 => 
            array (
                'id' => 64,
                'name' => '{"en":"Paraguay","pl":"Paraguay","ja":"Paraguay","es":"Paraguay","th":"Paraguay"}',
                'created_at' => '2018-06-07 16:25:33',
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'PRY',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 5,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            58 => 
            array (
                'id' => 65,
                'name' => '{"en":"Suriname","pl":"Suriname","ja":"Suriname","es":"Suriname","th":"Suriname"}',
                'created_at' => '2018-06-07 16:28:25',
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'SUR',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 5,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            59 => 
            array (
                'id' => 66,
                'name' => '{"en":"Uruguay","pl":"Uruguay","ja":"Uruguay","es":"Uruguay","th":"Uruguay"}',
                'created_at' => '2018-06-07 16:53:05',
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'URY',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 5,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            60 => 
            array (
                'id' => 67,
                'name' => '{"en":"Guyana","pl":"Guyana","ja":"Guyana","es":"Guyana","th":"Guyana"}',
                'created_at' => '2018-06-07 16:56:01',
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'GUY',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 5,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 1,
                'has_residence' => 1,
            ),
            61 => 
            array (
                'id' => 68,
                'name' => '{"en":"Russia","pl":"Rosja","ja":"\\u30ed\\u30b7\\u30a2","es":"Rusia","th":"Russia"}',
                'created_at' => '2018-08-13 16:29:34',
                'updated_at' => '2020-10-05 23:50:22',
                'iso3' => 'RUS',
                'currency' => 'usd',
                'is_active' => 1,
                'min_checkout_price' => '1.00',
                'max_checkout_price' => '10000.00',
                'max_checkout_unit_count' => 1000,
                'show_subscribing_ontraport' => 0,
                'has_shipping' => 0,
                'has_residence' => 1,
            ),
        ));
        
        
    }
}